" When opening Vim from inside Houdini, it overrides certain variables. Here
" we override those overrides with the proper values
if $HOME =~ 'houdini$'
    " Houdini overrides the $HOME variable
    let $HOME='C:/Users/eduardo.miyashiro'
    " Fixes plugins not being loaded
    let &runtimepath = 'C:/Users/eduardo.miyashiro/vimfiles,' . &runtimepath

    py import sys; sys.path.append('C:/Users/eduardo.miyashiro/vimfiles/plugin/usd/py')
    py import sys; sys.path.append('C:/Users/eduardo.miyashiro/vimsda/py')
    " Fixes 'No Qt binding were found' error
    py import sys; sys.path.append('C:/Users/eduardo.miyashiro/vim_pyenv/Lib/site-packages')

    " Houdini overrides the $HOME variable
    py import os; os.environ['HOME'] = 'C:/Users/eduardo.miyashiro'
    " Add paths to programs
    py import os; os.environ['PATH'] += ';C:/Users/eduardo.miyashiro/vimfiles/plugged/fzf/bin'
    py import os; os.environ['PATH'] += ';C:/Users/eduardo.miyashiro/vim_libs/node'
    py import os; os.environ['PATH'] += ';C:/Users/eduardo.miyashiro/vim_libs/ripgrep'
    py import os; os.environ['PATH'] += ';C:/Users/eduardo.miyashiro/vim_libs/bat'
endif

